package dataProject;

import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedList;

import dataProject.Contacts.Node;

public class CallLog extends javax.swing.JFrame {

    /**
     * Creates new form CallLog
     * @throws IOException 
     * @throws ClassNotFoundException 
     */
    public CallLog() throws ClassNotFoundException, IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws ClassNotFoundException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws IOException, ClassNotFoundException {
    	setTitle("Make Call");
    	 ContactMethods cm = new ContactMethods();
    	Contacts contact = cm.retreiveData();
    	String[] str = contact.getNames(contact.root);
        System.out.println(Arrays.toString(str)); 
    	jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        for(int x = 0 ; x < str.length ; x++)
        jComboBox1.addItem(str[x]);
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        
        getContentPane().setLayout(new AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status: ");
        getContentPane().add(jLabel3, new AbsoluteConstraints(60, 180, 230, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(str));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new AbsoluteConstraints(120, 120, 160, -1));

        jButton1.setText("Call");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               String str = (String)jComboBox1.getSelectedItem();
               try {
				cm.addCallLogs(str, contact.getContactNumber(contact.root, str));
			} catch (IOException e) {
				e.printStackTrace();
			}
               
               jLabel3.setText("STATUS: Called " + str +"(" + contact.getContactNumber(contact.root, str + ")"));
               
            }
        });
        getContentPane().add(jButton1, new AbsoluteConstraints(160, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Make Call");
        getContentPane().add(jLabel2, new AbsoluteConstraints(20, 20, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sk computer\\Desktop\\512x512bb.jpg")); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new CallLog().setVisible(true);
				} catch (ClassNotFoundException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}