/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataProject;

/**
 *
 * @author sk computer
 */
import java.awt.*;
import java.io.IOException;

import javax.swing.*;
public class ContactGUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactGUI
     */
    public ContactGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();  
        jButton1 = new javax.swing.JButton();  
        jButton3 = new javax.swing.JButton();  
        jButton8 = new javax.swing.JButton();  
        jButton4 = new javax.swing.JButton(); 
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Management");
        getContentPane().setLayout(new AbsoluteLayout());

        jButton2.setText("Delete Contact");  
        getContentPane().add(jButton2, new AbsoluteConstraints(460, 200, 150, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					new DeleteContact().setVisible(true);
				} catch (ClassNotFoundException e) {
					e.printStackTrace();
				} catch (IOException e) {
				}
            	//jButton2ActionPerformed(evt);
            }
        });
        jButton1.setText("Search Contact");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					SearchContact sc = new SearchContact();
					sc.setVisible(true); 
                } catch (ClassNotFoundException e) {
					e.printStackTrace();
				} catch (IOException e) {
					e.printStackTrace();
				}
                
            	jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new AbsoluteConstraints(10, 140, 150, 40));

        /*jButton3.setText("Display All Contacts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new AbsoluteConstraints(10, 200, 150, 40));		
        	*/																			
        jButton8.setText("Edit Contact");												
        jButton8.addActionListener(new java.awt.event.ActionListener() {					
            public void actionPerformed(java.awt.event.ActionEvent evt) {					
                 try { 																		
					AddContact ac = new AddContact();    										
					ac.setVisible(true);                 									 	
				} catch (IOException e) {                										
					// TODO Auto-generated catch block   													    
					e.printStackTrace();               											
				} catch (ClassNotFoundException e) {   		
					// TODO Auto-generated catch block  	
					e.printStackTrace();					
				}												
                 											
            	jButton8ActionPerformed(evt);				
            }
        });
        getContentPane().add(jButton8, new AbsoluteConstraints(10, 80, 150, 40));
        	
        jButton4.setText("View Contacts");													
        jButton4.addActionListener(new java.awt.event.ActionListener() {								
            public void actionPerformed(java.awt.event.ActionEvent evt) {					
                try {															
					jButton4ActionPerformed(evt);  				
				} catch (ClassNotFoundException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });		
        getContentPane().add(jButton4, new AbsoluteConstraints(10, 20, 150, 40));

        jButton5.setText("Favorite List");
        getContentPane().add(jButton5, new AbsoluteConstraints(460, 80, 150, 40));

        jButton6.setText("Dial Number");
        getContentPane().add(jButton6, new AbsoluteConstraints(460, 140, 150, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {					
            public void actionPerformed(java.awt.event.ActionEvent evt) {					
                 try { 																		
					CallLog calllog = new CallLog();    										
					calllog.setVisible(true);                 									 	
				} catch (IOException e) {                										
					// TODO Auto-generated catch block   													    
					e.printStackTrace();               											
				} catch (ClassNotFoundException e) {   		
					// TODO Auto-generated catch block  	
					e.printStackTrace();					
				}												              											
            	jButton8ActionPerformed(evt);				
            }
        });
        jButton7.setText("Call Logs");
        jButton7.addActionListener(new java.awt.event.ActionListener() {								
            public void actionPerformed(java.awt.event.ActionEvent evt) {					
                try {					
                	DisplayCallLogs cl = new DisplayCallLogs();
                	cl.setVisible(true);
				//	jButton4ActionPerformed(evt);  				
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });	
        getContentPane().add(jButton7, new AbsoluteConstraints(460, 20, 150, 40));
        
        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Ahsan Abbasi");
        getContentPane().add(jLabel2, new AbsoluteConstraints(10, 490, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jLabel6.setText("Prepared by: ");
        getContentPane().add(jLabel6, new AbsoluteConstraints(10, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Muskan");
        getContentPane().add(jLabel3, new AbsoluteConstraints(10, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Midhat Fatima");
        getContentPane().add(jLabel4, new AbsoluteConstraints(10, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Deepak");
        getContentPane().add(jLabel5, new AbsoluteConstraints(10, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\Project\\dataProject\\ContactGUI\\9017fdedab7868b6ff2f1b87313188de.jpg")); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(0, 0, -1, 600));

        setSize(new java.awt.Dimension(645, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, IOException {                                         
    	 DisplayContacts dc = new DisplayContacts();
         dc.setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
