/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataProject;

import java.io.IOException;

/**
 *
 * @author sk computer
 */
public class DeleteContact extends javax.swing.JFrame {

    /**
     * Creates new form DeleteContact
     * @throws ClassNotFoundException 
     */
    public DeleteContact() throws IOException, ClassNotFoundException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws IOException 
     * @throws ClassNotFoundException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws ClassNotFoundException, IOException {
    	setTitle("Delete Contact");
        
    	ContactMethods cm = new ContactMethods();
    	Contacts contact = cm.retreiveData();
    	String[] str = contact.getNames(contact.root);
    	
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(str));
        getContentPane().add(jComboBox1, new AbsoluteConstraints(110, 130, 190, -1));
        
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					cm.delContact(contact, (String)jComboBox1.getSelectedItem());
					jLabel2.setText("Status: " + jComboBox1.getSelectedItem() + " deleted.");
                } catch (IOException e) {
					e.printStackTrace();
				}
            	jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new AbsoluteConstraints(160, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("StatUS: ");
        getContentPane().add(jLabel3, new AbsoluteConstraints(60, 200, 340, -1));
        
        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Select Contact To Delete");
        getContentPane().add(jLabel2, new AbsoluteConstraints(110, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\Project\\dataProject\\DeleteContact\\512x512bb.jpg")); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(0, 0, 400, 300));
        
        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new DeleteContact().setVisible(true);
				} catch (ClassNotFoundException | IOException e) {
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}
