/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package dataProject;

	import java.io.IOException;
	
	/**
	 *
	 * @author sk computer
	 */
	public class DisplayContacts extends javax.swing.JFrame {
	
	    /** Creates new form DisplayContacts 
	     * @throws IOException 
	     * @throws ClassNotFoundException */
	    public DisplayContacts() throws ClassNotFoundException, IOException {
	        initComponents();
	    }
	
	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     * @throws IOException 
	     * @throws ClassNotFoundException 
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() throws ClassNotFoundException, IOException {
	    	ContactMethods cm = new ContactMethods();
	    	Contacts contact = cm.retreiveData();
	        jLabel1 = new javax.swing.JLabel();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jTextArea2 = new javax.swing.JTextArea();
	        
	        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
	
	        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
	        jLabel1.setText("All Contacts");
	         
	        jTextArea2.setEditable(false);
	        
	        jTextArea2.setColumns(50);
	        jTextArea2.setRows(50);
	        String str =contact.getcontactInformation(contact.root);
	        str =  str.replaceAll("null", "");
	        jTextArea2.setText(str);
	      
	       // jTextArea2.setText("Hi");
	        jScrollPane2.setViewportView(jTextArea2);
	        
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addContainerGap(275, Short.MAX_VALUE)
	                .addComponent(jLabel1)
	                .addGap(273, 273, 273))
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(12, 12, 12)
	                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap())
	        );
	
	        pack();
	    }// </editor-fold>                        
	
	    /**
	     * @param args the command line arguments
	     * @throws IOException 
	     * @throws ClassNotFoundException 
	     */
	    public static void main(String args[]) throws ClassNotFoundException, IOException {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	    	
	    	
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DisplayContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DisplayContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DisplayContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DisplayContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	
	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                try {
						new DisplayContacts().setVisible(true);
					} catch (ClassNotFoundException | IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
	            }
	        });
	    }
	
	    // Variables declaration - do not modify                     
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTextArea jTextArea2;
	    // End of variables declaration                   
	
	}
